name: Next.js Docker CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # O Docker Buildx permite builds mais rápidos e suporte a cache avançado
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Cache das camadas do Docker para acelerar os próximos builds
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build da Imagem Pet Joyful
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Apenas testa o build, não envia para um registro ainda
          tags: pet-joyful-frontend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # Estratégia para manter o cache do Docker atualizado
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache